# Generated by Django 3.2.6 on 2024-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBanco', '0002_auto_20240315_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibanco',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
