# Generated by Django 3.2.6 on 2024-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20240314_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasenia',
            field=models.CharField(max_length=10),
        ),
    ]
